### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by divgay** [audreyr/docker-bamboo-agent#1]
Hi,
I tried installing bamboo from your repo. Please place a solution for this error.

[root@manager ~]# docker run -e BAMBOO_SERVER=123.45.67.89 -t bamboo-agent
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed to connect to 123.45.67.89 port 8085: Connection timed out

**Comment by pydanny** [comment]
This project hasn't been touched in three years. 

May I suggest contacting Atlassian directly and requesting assistance?
